### ISSUE TITLE
Generate confusion matrix data

### ISSUE THREAD

**Issue by alessandro1802** [alessandro1802/analysis-of-fairness-measures#1]
For a given `n` generate all possible binary group confusion matrices, e.g for `n = 10`
| TP_m | TN_m | FP_m | FN_m | TP_f | TNf_| FP_f | FN_f |
|---|---|---|---|---|---|---|---| 
| 10 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 9 | 1 | 0 | 0 | 0 | 0 | 0 | 0 |
|...|...|...|...|...|...|...|...|

**Comment by dabrze** [comment]
There is already fancy numpy code for this purpose, which you will find in the original repo ;)
